/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testgit;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public int sumar() {
        return 2+2;
    }
}
