/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testgit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    
    void SumaCorrecta() {
        App classUnderTest = new App();
        assertEquals(7, classUnderTest.sumar(3,3));
    }
}

